server.port=8080
spring.cloud.gateway.routes[0].id=userservice
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=activityservice
spring.cloud.gateway.routes[1].uri=lb://ACTIVITYSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activities/**

spring.cloud.gateway.routes[2].id=aiservice
spring.cloud.gateway.routes[2].uri=lb://AISERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recommendations/**