spring.data.mongodb.uri=mongodb://localhost:27017/fitness_activity
spring.data.mongodb.database=fitness_activity
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
eureka.instance.prefer-ip-address=true
